// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OsmPlayground.Data.Context;

#nullable disable

namespace OsmPlayground.Data.Migrations
{
    [DbContext(typeof(OsmDbContext))]
    partial class OsmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmNode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Changeset")
                        .HasColumnType("bigint")
                        .HasColumnName("changeset");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_incomplete");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("tags");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_osm_nodes");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_osm_nodes_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_osm_nodes_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Tags"), new[] { "gin_hstore_ops" });

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_osm_nodes_user_id");

                    b.ToTable("osm_nodes", (string)null);
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Changeset")
                        .HasColumnType("bigint")
                        .HasColumnName("changeset");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_incomplete");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("tags");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_osm_relations");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_osm_relations_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Tags"), new[] { "gin_hstore_ops" });

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_osm_relations_user_id");

                    b.ToTable("osm_relations", (string)null);
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationMember", b =>
                {
                    b.Property<long>("RelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("relation_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<long>("RefId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_id");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("RelationId", "Index")
                        .HasName("pk_osm_relation_members");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_osm_relation_members_type");

                    b.ToTable("osm_relation_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_osm_relation_members_ref_matches_type", "(type = 1 AND (node_ref_id IS NULL OR node_ref_id = ref_id) AND way_ref_id IS NULL AND relation_ref_id IS NULL) OR (type = 2 AND (way_ref_id IS NULL OR way_ref_id = ref_id) AND node_ref_id IS NULL AND relation_ref_id IS NULL) OR (type = 3 AND (relation_ref_id IS NULL OR relation_ref_id = ref_id) AND node_ref_id IS NULL AND way_ref_id IS NULL)");
                        });

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationMemberTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_osm_relation_member_types");

                    b.ToTable("osm_relation_member_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Node"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Way"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Relation"
                        });
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.HasKey("Id")
                        .HasName("pk_osm_users");

                    b.ToTable("osm_users", (string)null);
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmWay", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Changeset")
                        .HasColumnType("bigint")
                        .HasColumnName("changeset");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry(Geometry, 4326)")
                        .HasColumnName("geometry");

                    b.Property<bool>("IsIncomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_incomplete");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("tags");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean")
                        .HasColumnName("visible");

                    b.HasKey("Id")
                        .HasName("pk_osm_ways");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_osm_ways_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_osm_ways_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Tags"), new[] { "gin_hstore_ops" });

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_osm_ways_user_id");

                    b.ToTable("osm_ways", (string)null);
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmWayNode", b =>
                {
                    b.Property<long>("WayId")
                        .HasColumnType("bigint")
                        .HasColumnName("way_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<long?>("NodeRefId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_ref_id");

                    b.HasKey("WayId", "Index")
                        .HasName("pk_osm_way_nodes");

                    b.HasIndex("NodeRefId")
                        .HasDatabaseName("ix_osm_way_nodes_node_ref_id");

                    b.ToTable("osm_way_nodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_osm_way_nodes_node_ref_matches_node_id", "node_ref_id IS NULL OR node_ref_id = node_id");
                        });
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationNodeRef", b =>
                {
                    b.HasBaseType("OsmPlayground.Data.Entities.OsmRelationMember");

                    b.Property<long?>("NodeRefId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_ref_id");

                    b.HasIndex("NodeRefId")
                        .HasDatabaseName("ix_osm_relation_members_node_ref_id");

                    b.ToTable("osm_relation_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_osm_relation_members_ref_matches_type", "(type = 1 AND (node_ref_id IS NULL OR node_ref_id = ref_id) AND way_ref_id IS NULL AND relation_ref_id IS NULL) OR (type = 2 AND (way_ref_id IS NULL OR way_ref_id = ref_id) AND node_ref_id IS NULL AND relation_ref_id IS NULL) OR (type = 3 AND (relation_ref_id IS NULL OR relation_ref_id = ref_id) AND node_ref_id IS NULL AND way_ref_id IS NULL)");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationRelationRef", b =>
                {
                    b.HasBaseType("OsmPlayground.Data.Entities.OsmRelationMember");

                    b.Property<long?>("RelationRefId")
                        .HasColumnType("bigint")
                        .HasColumnName("relation_ref_id");

                    b.HasIndex("RelationRefId")
                        .HasDatabaseName("ix_osm_relation_members_relation_ref_id");

                    b.ToTable("osm_relation_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_osm_relation_members_ref_matches_type", "(type = 1 AND (node_ref_id IS NULL OR node_ref_id = ref_id) AND way_ref_id IS NULL AND relation_ref_id IS NULL) OR (type = 2 AND (way_ref_id IS NULL OR way_ref_id = ref_id) AND node_ref_id IS NULL AND relation_ref_id IS NULL) OR (type = 3 AND (relation_ref_id IS NULL OR relation_ref_id = ref_id) AND node_ref_id IS NULL AND way_ref_id IS NULL)");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationWayRef", b =>
                {
                    b.HasBaseType("OsmPlayground.Data.Entities.OsmRelationMember");

                    b.Property<long?>("WayRefId")
                        .HasColumnType("bigint")
                        .HasColumnName("way_ref_id");

                    b.HasIndex("WayRefId")
                        .HasDatabaseName("ix_osm_relation_members_way_ref_id");

                    b.ToTable("osm_relation_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_osm_relation_members_ref_matches_type", "(type = 1 AND (node_ref_id IS NULL OR node_ref_id = ref_id) AND way_ref_id IS NULL AND relation_ref_id IS NULL) OR (type = 2 AND (way_ref_id IS NULL OR way_ref_id = ref_id) AND node_ref_id IS NULL AND relation_ref_id IS NULL) OR (type = 3 AND (relation_ref_id IS NULL OR relation_ref_id = ref_id) AND node_ref_id IS NULL AND way_ref_id IS NULL)");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmNode", b =>
                {
                    b.HasOne("OsmPlayground.Data.Entities.OsmUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_osm_nodes_osm_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelation", b =>
                {
                    b.HasOne("OsmPlayground.Data.Entities.OsmUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_osm_relations_osm_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationMember", b =>
                {
                    b.HasOne("OsmPlayground.Data.Entities.OsmRelation", null)
                        .WithMany("Members")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_osm_relation_members_osm_relations_relation_id");

                    b.HasOne("OsmPlayground.Data.Entities.OsmRelationMemberTypeLookup", "TypeLookup")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_osm_relation_members_osm_relation_member_type_lookup_type");

                    b.Navigation("TypeLookup");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmWay", b =>
                {
                    b.HasOne("OsmPlayground.Data.Entities.OsmUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_osm_ways_osm_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmWayNode", b =>
                {
                    b.HasOne("OsmPlayground.Data.Entities.OsmNode", "Node")
                        .WithMany("WayNodes")
                        .HasForeignKey("NodeRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_osm_way_nodes_osm_nodes_node_ref_id");

                    b.HasOne("OsmPlayground.Data.Entities.OsmWay", "Way")
                        .WithMany("WayNodes")
                        .HasForeignKey("WayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_osm_way_nodes_osm_ways_way_id");

                    b.Navigation("Node");

                    b.Navigation("Way");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationNodeRef", b =>
                {
                    b.HasOne("OsmPlayground.Data.Entities.OsmNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_osm_relation_members_osm_nodes_node_ref_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationRelationRef", b =>
                {
                    b.HasOne("OsmPlayground.Data.Entities.OsmRelation", "Relation")
                        .WithMany()
                        .HasForeignKey("RelationRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_osm_relation_members_osm_relations_relation_ref_id");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelationWayRef", b =>
                {
                    b.HasOne("OsmPlayground.Data.Entities.OsmWay", "Way")
                        .WithMany()
                        .HasForeignKey("WayRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_osm_relation_members_osm_ways_way_ref_id");

                    b.Navigation("Way");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmNode", b =>
                {
                    b.Navigation("WayNodes");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmRelation", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("OsmPlayground.Data.Entities.OsmWay", b =>
                {
                    b.Navigation("WayNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
